.catch(_err => {
  // Error handling here
}); 